import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Section1 from '../components/Section1';
import Navbar from '../components/Navbar';
import Mentors from './Mentors';
import About from '../components/About'
import Footer from '../components/Footer'

export default function Home() {

  return (
    <div className='absolute right-0 m-0 p-0 '>
      <Head>
        <title>Quran Tutor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main  className='w-full m-0 p-0 overflow-x-hidden'>

        <Navbar />
        <Section1 />
        <Mentors />
        <About />
        <Footer />

        </main>
    </div>
  )
}
